language: csharp
script:
    - xbuild /p:Configuration=Release vMenu.sln
notifications:
  webhooks:
    urls:
      - https://vespura.com/travis-ci.php
branches:
    only:
        - master
        - production
        #- development
before_deploy:
    - mkdir /home/travis/build/TomGrobbe/vMenu/builds
    - mkdir /home/travis/build/TomGrobbe/vMenu/builds/config
    - cp /home/travis/build/TomGrobbe/vMenu/vMenu/bin/Release/vMenuClient.net.dll /home/travis/build/TomGrobbe/vMenu/builds/
    - cp /home/travis/build/TomGrobbe/vMenu/vMenu/bin/Release/NativeUI.dll /home/travis/build/TomGrobbe/vMenu/builds/
    - cp /home/travis/build/TomGrobbe/vMenu/vMenuServer/bin/Release/Newtonsoft.Json.dll /home/travis/build/TomGrobbe/vMenu/builds/
    - cp /home/travis/build/TomGrobbe/vMenu/vMenuServer/bin/Release/config/permissions.cfg /home/travis/build/TomGrobbe/vMenu/builds/config/
    - cp /home/travis/build/TomGrobbe/vMenu/vMenuServer/bin/Release/System.Numerics.dll /home/travis/build/TomGrobbe/vMenu/builds/
    - cp /home/travis/build/TomGrobbe/vMenu/vMenuServer/bin/Release/vMenuServer.net.dll /home/travis/build/TomGrobbe/vMenu/builds/
    - cd /home/travis/build/TomGrobbe/vMenu/builds && wget https://vespura.com/vmenu/__resource.lua && zip -r vMenu-release.zip *
    - git config --local user.name "TomGrobbe"
    - git config --local user.email "tom.grobbe@gmail.com"
    - git tag "vMenu$(git log --format=%h -1)"
deploy:
    provider: releases
    api_key: $GITHUB_API_KEY
    file: "/home/travis/build/TomGrobbe/vMenu/builds/vMenu-release.zip"
    skip_cleanup: true
    prerelease: true
    draft: true
    name: "[Alpha] vMenu v0.1.x"
    on:
        branch: production
        # tags: true